CREATE TABLE `ai_code_artifact` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `artifact_id` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Artifact 业务编号',
  `artifact_source_type` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Artifact 来源类型',
  `artifact_status` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Artifact 状态',
  `session_id` bigint NOT NULL COMMENT '会话表编号',
  `source_command_id` bigint NOT NULL COMMENT '产生文件变更的原始 Prompt 命令表编号',
  `transfer_command_id` bigint DEFAULT NULL COMMENT '执行 Artifact 获取的远程命令表编号',
  `change_set_id` bigint NOT NULL COMMENT '变更集表编号',
  `file_change_id` bigint NOT NULL COMMENT '文件变更表编号',
  `device_id` bigint NOT NULL COMMENT '设备表编号',
  `project_id` bigint NOT NULL COMMENT '项目表编号',
  `owner_user_id` bigint NOT NULL COMMENT '所属用户编号',
  `relative_path` varchar(1024) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Workspace 相对路径',
  `file_name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '文件名称',
  `content_type` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'MIME 类型',
  `file_size` bigint DEFAULT NULL COMMENT '文件大小，字节',
  `sha256` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Artifact SHA-256',
  `file_id` bigint DEFAULT NULL COMMENT '项目统一文件记录编号',
  `client_request_id` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '客户端幂等请求编号',
  `source_last_modified_time` datetime DEFAULT NULL COMMENT 'Daemon 获取文件时源文件最后修改时间',
  `requested_time` datetime NOT NULL COMMENT '请求时间',
  `upload_started_time` datetime DEFAULT NULL COMMENT '开始上传时间',
  `ready_time` datetime DEFAULT NULL COMMENT '上传完成时间',
  `expire_time` datetime DEFAULT NULL COMMENT 'Artifact 过期时间',
  `error_code` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '失败错误码',
  `error_message` varchar(1024) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '失败摘要',
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AI Coding Artifact 表';
