CREATE TABLE `ai_code_permission_request` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
    `permission_id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '权限请求业务编号',
    `session_id` bigint NOT NULL COMMENT '会话表编号',
    `command_id` bigint DEFAULT NULL COMMENT '触发权限请求的原始命令表编号',
    `device_id` bigint NOT NULL COMMENT '设备表编号',
    `project_id` bigint NOT NULL COMMENT '项目表编号',
    `owner_user_id` bigint NOT NULL COMMENT '所属用户编号',
    `permission_type` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '权限类型',
    `permission_status` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'PENDING' COMMENT '权限请求状态',
    `title` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '权限请求标题',
    `reason` varchar(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '权限请求原因',
    `request_json` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '平台脱敏后的权限请求详情 JSON，不保存 Codex 原始请求',
    `decision` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '用户决策',
    `decision_reason` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '用户决策说明',
    `decision_user_id` bigint DEFAULT NULL COMMENT '执行审批的用户编号',
    `decision_command_id` bigint DEFAULT NULL COMMENT '权限决策远程命令表编号',
    `requested_time` datetime NOT NULL COMMENT '请求时间',
    `decided_time` datetime DEFAULT NULL COMMENT '用户决策时间',
    `resolved_time` datetime DEFAULT NULL COMMENT 'Codex 确认请求结束时间',
    `error_message` varchar(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '失败摘要',
    `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT '' COMMENT '创建者',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT '' COMMENT '更新者',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
    `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Agent 权限审批请求表';
