CREATE TABLE `ai_code_project` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `device_id` bigint NOT NULL COMMENT '设备表编号，关联 ai_code_device.id',
  `project_id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '项目业务编号',
  `local_project_id` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Daemon 本地项目稳定编号',
  `owner_user_id` bigint NOT NULL COMMENT '项目所属用户编号',
  `project_name` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '项目名称',
  `workspace_path` varchar(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Daemon 本地工作目录，由本地发现后上报，云端只作为标识和展示，执行时仍由 Daemon 再校验',
  `workspace_real_path` varchar(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '最近一次 Daemon 规范化后的真实路径，可为空',
  `agent_type` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'CODEX' COMMENT '默认 Agent 类型',
  `project_status` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'ACTIVE' COMMENT '项目状态，ACTIVE/DISABLED',
  `last_seen_time` datetime NULL COMMENT 'Daemon 最近确认该项目存在时间',
  `remark` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT '' COMMENT '备注',
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AI Coding Remote 项目';

CREATE TABLE `ai_code_runtime` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `device_id` bigint NOT NULL COMMENT '设备表编号',
  `runtime_id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Runtime 业务编号',
  `runtime_type` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '运行时类型，例如 CODEX_APP_SERVER',
  `runtime_version` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '运行时版本，例如 Codex CLI 版本',
  `executable_path` varchar(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '本地 executable 标识或路径，注意仅用于诊断，不接受云端任意覆盖执行',
  `runtime_status` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'AVAILABLE' COMMENT 'AVAILABLE/UNAVAILABLE/DISABLED',
  `capabilities_json` varchar(4096) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '最近探测到的平台能力快照，只保存平台 AgentCapabilities JSON，不保存 Codex 原生协议对象',
  `last_discovered_time` datetime NULL COMMENT '最近探测时间',
  `remark` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT '' COMMENT '备注',
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AI Coding Remote Agent Runtime';

CREATE TABLE `ai_code_session` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `session_id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '平台 Session 业务编号',
  `device_id` bigint NOT NULL COMMENT '设备表编号',
  `project_id` bigint NOT NULL COMMENT 'ai_code_project.id',
  `runtime_id` bigint NULL COMMENT 'ai_code_runtime.id',
  `owner_user_id` bigint NOT NULL COMMENT 'Session 所属用户编号',
  `agent_type` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Agent 类型',
  `native_session_id` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '本地 Agent Native Session，例如 Codex thread id，仅作为受控映射，不对用户作为主身份',
  `session_status` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'CREATED' COMMENT 'CREATED/STARTING/RUNNING/IDLE/FAILED/CLOSED/EVENT_GAP',
  `last_event_seq` bigint NOT NULL DEFAULT 0 COMMENT 'Control Plane 已接受的最大连续 AgentEvent seq',
  `last_active_time` datetime NULL COMMENT '最近活跃时间',
  `started_time` datetime NULL COMMENT '启动时间',
  `closed_time` datetime NULL COMMENT '关闭时间',
  `error_message` varchar(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '最后一次可公开的错误摘要，禁止存 credential/token/native 原始敏感内容',
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AI Coding Remote Agent Session';

CREATE TABLE `ai_code_command` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `command_id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '远程命令业务编号',
  `session_id` bigint NOT NULL COMMENT 'ai_code_session.id',
  `device_id` bigint NOT NULL COMMENT '设备表编号',
  `project_id` bigint NOT NULL COMMENT '项目表编号',
  `owner_user_id` bigint NOT NULL COMMENT '命令所属用户编号',
  `command_type` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'PROMPT/CANCEL/CLOSE_SESSION，当前优先实现 PROMPT',
  `command_status` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'CREATED' COMMENT 'CREATED/ROUTING/DELIVERED/ACKED/RUNNING/SUCCEEDED/FAILED/REJECTED/TIMEOUT',
  `request_id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '客户端幂等请求编号，可由调用方提供',
  `payload_json` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '平台 AgentCommand Payload JSON，只保存平台协议，不保存 Codex Native JSON',
  `ack_code` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT 'ACK 代码',
  `ack_message` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT 'ACK 消息',
  `created_dispatch_time` datetime NULL COMMENT '开始路由时间',
  `delivered_time` datetime NULL COMMENT '送达时间',
  `acked_time` datetime NULL COMMENT 'Daemon ACK 时间',
  `completed_time` datetime NULL COMMENT '完成时间',
  `error_message` varchar(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '错误摘要',
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AI Coding Remote 远程命令';

CREATE TABLE `ai_code_message` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `message_id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '消息业务编号',
  `session_id` bigint NOT NULL COMMENT 'ai_code_session.id',
  `command_id` bigint NULL COMMENT 'ai_code_command.id',
  `role` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'USER/ASSISTANT/SYSTEM/TOOL',
  `message_type` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'TEXT/ERROR/COMMAND_OUTPUT 等平台消息类型',
  `content` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '最终消息内容',
  `event_seq` bigint NULL COMMENT '产生该最终消息的 AgentEvent seq',
  `message_status` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'FINAL' COMMENT '本阶段只持久化最终消息，流式 DELTA 默认不入 MySQL',
  `native_item_id` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '允许保存白名单 Native Item ID 用于诊断，不保存完整 Native Item',
  `create_source` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'AGENT_EVENT' COMMENT 'USER_COMMAND/AGENT_EVENT',
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AI Coding Remote 消息';
